"""initial schema

Revision ID: 33c61f3cb231
Revises: 
Create Date: 2026-08-07 17:28:00.917022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33c61f3cb231'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_templates',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slot', sa.Enum('weapon', 'helmet', 'shield', 'armor', 'amulet', 'spell_skill', name='equipment_slot'), nullable=False),
    sa.Column('rarity', sa.Enum('common', 'uncommon', 'rare', 'epic', 'legendary', name='item_rarity'), nullable=False),
    sa.Column('base_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('level_requirement', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_item_templates_slug'))
    )
    op.create_table('monster_templates',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level_range_min', sa.Integer(), nullable=False),
    sa.Column('level_range_max', sa.Integer(), nullable=False),
    sa.Column('base_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_monster_templates_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('heroes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.BigInteger(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('vitality', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('spirit', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('agility >= 0', name=op.f('ck_heroes_agility_gte_0')),
    sa.CheckConstraint('dexterity >= 0', name=op.f('ck_heroes_dexterity_gte_0')),
    sa.CheckConstraint('intelligence >= 0', name=op.f('ck_heroes_intelligence_gte_0')),
    sa.CheckConstraint('level >= 1', name=op.f('ck_heroes_level_gte_1')),
    sa.CheckConstraint('spirit >= 0', name=op.f('ck_heroes_spirit_gte_0')),
    sa.CheckConstraint('strength >= 0', name=op.f('ck_heroes_strength_gte_0')),
    sa.CheckConstraint('vitality >= 0', name=op.f('ck_heroes_vitality_gte_0')),
    sa.CheckConstraint('xp >= 0', name=op.f('ck_heroes_xp_gte_0')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_heroes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heroes')),
    sa.UniqueConstraint('user_id', name=op.f('uq_heroes_user_id'))
    )
    op.create_table('monster_loot_entries',
    sa.Column('monster_template_id', sa.UUID(), nullable=False),
    sa.Column('item_template_id', sa.UUID(), nullable=False),
    sa.Column('drop_weight', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_template_id'], ['item_templates.id'], name=op.f('fk_monster_loot_entries_item_template_id_item_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_template_id'], ['monster_templates.id'], name=op.f('fk_monster_loot_entries_monster_template_id_monster_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_loot_entries'))
    )
    op.create_table('veil_runs',
    sa.Column('hero_id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='veil_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('resolves_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds > 0', name=op.f('ck_veil_runs_duration_seconds_gt_0')),
    sa.CheckConstraint('resolves_at > started_at', name=op.f('ck_veil_runs_resolves_at_after_started_at')),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], name=op.f('fk_veil_runs_hero_id_heroes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_veil_runs'))
    )
    op.create_index('ix_veil_runs_hero_started_at', 'veil_runs', ['hero_id', 'started_at'], unique=False)
    op.create_index('uq_hero_one_active_run', 'veil_runs', ['hero_id'], unique=True, postgresql_where="status = 'in_progress'")
    op.create_table('item_instances',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('owner_hero_id', sa.UUID(), nullable=True),
    sa.Column('equipped_slot', sa.Enum('weapon', 'helmet', 'shield', 'armor', 'amulet', 'spell_skill', name='equipment_slot'), nullable=True),
    sa.Column('rolled_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_veil_run_id', sa.UUID(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('equipped_slot IS NULL OR owner_hero_id IS NOT NULL', name=op.f('ck_item_instances_equipped_requires_owner')),
    sa.ForeignKeyConstraint(['owner_hero_id'], ['heroes.id'], name=op.f('fk_item_instances_owner_hero_id_heroes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_veil_run_id'], ['veil_runs.id'], name=op.f('fk_item_instances_source_veil_run_id_veil_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], name=op.f('fk_item_instances_template_id_item_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_instances'))
    )
    op.create_index('uq_hero_equipped_slot', 'item_instances', ['owner_hero_id', 'equipped_slot'], unique=True, postgresql_where='equipped_slot IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_hero_equipped_slot', table_name='item_instances', postgresql_where='equipped_slot IS NOT NULL')
    op.drop_table('item_instances')
    op.drop_index('uq_hero_one_active_run', table_name='veil_runs', postgresql_where="status = 'in_progress'")
    op.drop_index('ix_veil_runs_hero_started_at', table_name='veil_runs')
    op.drop_table('veil_runs')
    op.drop_table('monster_loot_entries')
    op.drop_table('heroes')
    op.drop_table('users')
    op.drop_table('monster_templates')
    op.drop_table('item_templates')
    # ### end Alembic commands ###
