"""add material templates and instances

Revision ID: 4b7389bf4468
Revises: 33c61f3cb231
Create Date: 2026-08-08 11:53:14.670306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7389bf4468'
down_revision: Union[str, Sequence[str], None] = '33c61f3cb231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_templates',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_material_templates_slug'))
    )
    op.create_table('material_instances',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('owner_hero_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_veil_run_id', sa.UUID(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_material_instances_quantity_gt_0')),
    sa.ForeignKeyConstraint(['owner_hero_id'], ['heroes.id'], name=op.f('fk_material_instances_owner_hero_id_heroes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_veil_run_id'], ['veil_runs.id'], name=op.f('fk_material_instances_source_veil_run_id_veil_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['material_templates.id'], name=op.f('fk_material_instances_template_id_material_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_instances'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_instances')
    op.drop_table('material_templates')
    # ### end Alembic commands ###
