"""add campaign nodes and hero gold/progress

Revision ID: 1ab7c0fdc2cf
Revises: 4b7389bf4468
Create Date: 2026-08-08 12:38:43.594473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab7c0fdc2cf'
down_revision: Union[str, Sequence[str], None] = '4b7389bf4468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_nodes',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('gold_cost', sa.Integer(), nullable=False),
    sa.Column('monster_template_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gold_cost >= 0', name=op.f('ck_campaign_nodes_gold_cost_gte_0')),
    sa.CheckConstraint('order_index > 0', name=op.f('ck_campaign_nodes_order_index_gt_0')),
    sa.CheckConstraint('required_level >= 1', name=op.f('ck_campaign_nodes_required_level_gte_1')),
    sa.ForeignKeyConstraint(['monster_template_id'], ['monster_templates.id'], name=op.f('fk_campaign_nodes_monster_template_id_monster_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_nodes')),
    sa.UniqueConstraint('order_index', name=op.f('uq_campaign_nodes_order_index')),
    sa.UniqueConstraint('slug', name=op.f('uq_campaign_nodes_slug'))
    )
    op.add_column('heroes', sa.Column('gold', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('heroes', sa.Column('campaign_progress', sa.Integer(), nullable=False, server_default='0'))
    op.create_check_constraint(op.f('ck_heroes_campaign_progress_gte_0'), 'heroes', 'campaign_progress >= 0')
    op.create_check_constraint(op.f('ck_heroes_gold_gte_0'), 'heroes', 'gold >= 0')
    op.add_column('veil_runs', sa.Column('campaign_node_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_veil_runs_campaign_node_id_campaign_nodes'), 'veil_runs', 'campaign_nodes', ['campaign_node_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_veil_runs_campaign_node_id_campaign_nodes'), 'veil_runs', type_='foreignkey')
    op.drop_column('veil_runs', 'campaign_node_id')
    op.drop_constraint(op.f('ck_heroes_gold_gte_0'), 'heroes', type_='check')
    op.drop_constraint(op.f('ck_heroes_campaign_progress_gte_0'), 'heroes', type_='check')
    op.drop_column('heroes', 'campaign_progress')
    op.drop_column('heroes', 'gold')
    op.drop_table('campaign_nodes')
    # ### end Alembic commands ###
