"""add hero available stat points

Revision ID: d80fa37cdc50
Revises: 1ab7c0fdc2cf
Create Date: 2026-08-08 15:31:27.028008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80fa37cdc50'
down_revision: Union[str, Sequence[str], None] = '1ab7c0fdc2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('available_stat_points', sa.Integer(), nullable=False, server_default='0'))
    op.create_check_constraint(op.f('ck_heroes_available_stat_points_gte_0'), 'heroes', 'available_stat_points >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_heroes_available_stat_points_gte_0'), 'heroes', type_='check')
    op.drop_column('heroes', 'available_stat_points')
    # ### end Alembic commands ###
