"""add hero inventory capacity

Revision ID: 0338c395cfb4
Revises: 1ab7c0fdc2cf
Create Date: 2026-08-09 05:27:16.647863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0338c395cfb4'
down_revision: Union[str, Sequence[str], None] = '1ab7c0fdc2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('inventory_capacity', sa.Integer(), nullable=False, server_default='20'))
    op.create_check_constraint(op.f('ck_heroes_inventory_capacity_gte_1'), 'heroes', 'inventory_capacity >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_heroes_inventory_capacity_gte_1'), 'heroes', type_='check')
    op.drop_column('heroes', 'inventory_capacity')
    # ### end Alembic commands ###
