"""add monster material loot entries

Revision ID: 8c92119ea89c
Revises: 0338c395cfb4
Create Date: 2026-08-09 08:55:42.564708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c92119ea89c'
down_revision: Union[str, Sequence[str], None] = '0338c395cfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_material_loot_entries',
    sa.Column('monster_template_id', sa.UUID(), nullable=False),
    sa.Column('material_template_id', sa.UUID(), nullable=False),
    sa.Column('drop_weight', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_template_id'], ['material_templates.id'], name=op.f('fk_monster_material_loot_entries_material_template_id_material_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_template_id'], ['monster_templates.id'], name=op.f('fk_monster_material_loot_entries_monster_template_id_monster_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_material_loot_entries'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster_material_loot_entries')
    # ### end Alembic commands ###
