"""add hero current hp

Revision ID: 552d1a5f24fe
Revises: 8c92119ea89c
Create Date: 2026-08-09 09:30:15.532583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552d1a5f24fe'
down_revision: Union[str, Sequence[str], None] = '8c92119ea89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # current_hp starts nullable so existing rows can be backfilled before
    # the NOT NULL constraint is enforced. Backfill uses today's BASE_HP=50 /
    # HP_PER_VITALITY=10 inlined as literal SQL rather than importing
    # hero_service - migrations are frozen historical snapshots and must
    # keep working even if that formula changes in a later commit. This
    # also ignores equipped-gear vitality bonuses (base vitality only) -
    # a hero with vitality gear simply starts slightly under their true max
    # and regens up to it, which is harmless.
    op.add_column('heroes', sa.Column('current_hp', sa.Integer(), nullable=True))
    op.add_column('heroes', sa.Column('hp_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("UPDATE heroes SET current_hp = 50 + vitality * 10")
    op.alter_column('heroes', 'current_hp', nullable=False)
    op.create_check_constraint(op.f('ck_heroes_current_hp_gte_0'), 'heroes', 'current_hp >= 0')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_heroes_current_hp_gte_0'), 'heroes', type_='check')
    op.drop_column('heroes', 'hp_updated_at')
    op.drop_column('heroes', 'current_hp')
    # ### end Alembic commands ###
