"""add crafting

Revision ID: a6618679f668
Revises: 552d1a5f24fe
Create Date: 2026-08-09 09:37:08.311348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6618679f668'
down_revision: Union[str, Sequence[str], None] = '552d1a5f24fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumable_templates',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('heal_amount_fraction', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumable_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_consumable_templates_slug'))
    )
    op.create_table('crafting_recipes',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('alchemy', 'forge', name='crafting_category'), nullable=False),
    sa.Column('level_requirement', sa.Integer(), nullable=False),
    sa.Column('output_consumable_template_id', sa.UUID(), nullable=False),
    sa.Column('output_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['output_consumable_template_id'], ['consumable_templates.id'], name=op.f('fk_crafting_recipes_output_consumable_template_id_consumable_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crafting_recipes')),
    sa.UniqueConstraint('slug', name=op.f('uq_crafting_recipes_slug'))
    )
    op.create_table('consumable_instances',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('owner_hero_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_consumable_instances_quantity_gt_0')),
    sa.ForeignKeyConstraint(['owner_hero_id'], ['heroes.id'], name=op.f('fk_consumable_instances_owner_hero_id_heroes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['consumable_templates.id'], name=op.f('fk_consumable_instances_template_id_consumable_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumable_instances'))
    )
    op.create_table('crafting_recipe_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('material_template_id', sa.UUID(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_template_id'], ['material_templates.id'], name=op.f('fk_crafting_recipe_ingredients_material_template_id_material_templates')),
    sa.ForeignKeyConstraint(['recipe_id'], ['crafting_recipes.id'], name=op.f('fk_crafting_recipe_ingredients_recipe_id_crafting_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crafting_recipe_ingredients'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crafting_recipe_ingredients')
    op.drop_table('consumable_instances')
    op.drop_table('crafting_recipes')
    op.drop_table('consumable_templates')
    # ### end Alembic commands ###
