"""add campaign chapters

Revision ID: 8e4f94869796
Revises: 43c09fa4859f
Create Date: 2026-08-10 16:15:59.936611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4f94869796'
down_revision: Union[str, Sequence[str], None] = '43c09fa4859f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adds campaign_chapters and links campaign_nodes to it via chapter_id;
    also drops campaign_nodes.gold_cost (campaign battles are no longer
    gold-gated). chapter_id is added NOT NULL directly since campaign_nodes
    is expected to be empty at this point (see 0015); if it isn't, this
    fails loudly rather than guessing which chapter existing rows belong to.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_chapters',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_index > 0', name=op.f('ck_campaign_chapters_order_index_gt_0')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_chapters')),
    sa.UniqueConstraint('order_index', name=op.f('uq_campaign_chapters_order_index')),
    sa.UniqueConstraint('slug', name=op.f('uq_campaign_chapters_slug'))
    )
    op.add_column('campaign_nodes', sa.Column('chapter_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_campaign_nodes_chapter_id_campaign_chapters'), 'campaign_nodes', 'campaign_chapters', ['chapter_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('ck_campaign_nodes_gold_cost_gte_0'), 'campaign_nodes', type_='check')
    op.drop_column('campaign_nodes', 'gold_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_nodes', sa.Column('gold_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('ck_campaign_nodes_gold_cost_gte_0'), 'campaign_nodes', 'gold_cost >= 0')
    op.drop_constraint(op.f('fk_campaign_nodes_chapter_id_campaign_chapters'), 'campaign_nodes', type_='foreignkey')
    op.drop_column('campaign_nodes', 'chapter_id')
    op.drop_table('campaign_chapters')
    # ### end Alembic commands ###
