"""add monster weapon attack and defense

Revision ID: 7326394099d7
Revises: 47570e97aeed
Create Date: 2026-08-11 07:08:57.653621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7326394099d7'
down_revision: Union[str, Sequence[str], None] = '47570e97aeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. Existing monster rows backfill to 0 for all three
    columns via server_default, preserving today's combat balance until
    someone explicitly tunes a monster's attack/defense."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_templates', sa.Column('weapon_attack_min', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('monster_templates', sa.Column('weapon_attack_max', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('monster_templates', sa.Column('defense', sa.Integer(), nullable=False, server_default='0'))
    op.create_check_constraint(op.f('ck_monster_templates_defense_non_negative'), 'monster_templates', 'defense >= 0')
    op.create_check_constraint(op.f('ck_monster_templates_weapon_attack_max_gte_min'), 'monster_templates', 'weapon_attack_max >= weapon_attack_min')
    op.create_check_constraint(op.f('ck_monster_templates_weapon_attack_min_non_negative'), 'monster_templates', 'weapon_attack_min >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_monster_templates_weapon_attack_min_non_negative'), 'monster_templates', type_='check')
    op.drop_constraint(op.f('ck_monster_templates_weapon_attack_max_gte_min'), 'monster_templates', type_='check')
    op.drop_constraint(op.f('ck_monster_templates_defense_non_negative'), 'monster_templates', type_='check')
    op.drop_column('monster_templates', 'defense')
    op.drop_column('monster_templates', 'weapon_attack_max')
    op.drop_column('monster_templates', 'weapon_attack_min')
    # ### end Alembic commands ###
