"""add monster spell attack

Revision ID: e6edf0b848fb
Revises: 7326394099d7
Create Date: 2026-08-11 09:21:32.237056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6edf0b848fb'
down_revision: Union[str, Sequence[str], None] = '7326394099d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. Existing monster rows backfill to 0 for both columns
    via server_default, preserving today's combat balance until someone
    explicitly tunes a monster's spell attack."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_templates', sa.Column('spell_attack_min', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('monster_templates', sa.Column('spell_attack_max', sa.Integer(), nullable=False, server_default='0'))
    op.create_check_constraint(op.f('ck_monster_templates_spell_attack_max_gte_min'), 'monster_templates', 'spell_attack_max >= spell_attack_min')
    op.create_check_constraint(op.f('ck_monster_templates_spell_attack_min_non_negative'), 'monster_templates', 'spell_attack_min >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_monster_templates_spell_attack_min_non_negative'), 'monster_templates', type_='check')
    op.drop_constraint(op.f('ck_monster_templates_spell_attack_max_gte_min'), 'monster_templates', type_='check')
    op.drop_column('monster_templates', 'spell_attack_max')
    op.drop_column('monster_templates', 'spell_attack_min')
    # ### end Alembic commands ###
