"""add runes

Revision ID: 98df2eb569cb
Revises: fc50534ac3ed
Create Date: 2026-08-15 07:02:33.477143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98df2eb569cb'
down_revision: Union[str, Sequence[str], None] = 'fc50534ac3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rune_templates',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stat_bonuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rune_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_rune_templates_slug'))
    )
    op.create_table('rune_instances',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('owner_hero_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_rune_instances_quantity_gt_0')),
    sa.ForeignKeyConstraint(['owner_hero_id'], ['heroes.id'], name=op.f('fk_rune_instances_owner_hero_id_heroes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['rune_templates.id'], name=op.f('fk_rune_instances_template_id_rune_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rune_instances'))
    )
    op.add_column('crafting_recipes', sa.Column('output_rune_template_id', sa.UUID(), nullable=True))
    op.alter_column('crafting_recipes', 'output_consumable_template_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_crafting_recipes_output_rune_template_id_rune_templates'), 'crafting_recipes', 'rune_templates', ['output_rune_template_id'], ['id'])
    op.create_check_constraint(op.f('ck_crafting_recipes_exactly_one_output'), 'crafting_recipes', '(output_consumable_template_id IS NULL) != (output_rune_template_id IS NULL)')
    op.add_column('item_instances', sa.Column('rune_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_item_instances_rune_template_id_rune_templates'), 'item_instances', 'rune_templates', ['rune_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_item_instances_rune_template_id_rune_templates'), 'item_instances', type_='foreignkey')
    op.drop_column('item_instances', 'rune_template_id')
    op.drop_constraint(op.f('ck_crafting_recipes_exactly_one_output'), 'crafting_recipes', type_='check')
    op.drop_constraint(op.f('fk_crafting_recipes_output_rune_template_id_rune_templates'), 'crafting_recipes', type_='foreignkey')
    op.alter_column('crafting_recipes', 'output_consumable_template_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('crafting_recipes', 'output_rune_template_id')
    op.drop_table('rune_instances')
    op.drop_table('rune_templates')
    # ### end Alembic commands ###
